version: "3"
services:
    # mongo:
    #     image: mongo
    #     container_name: mongo-muhna
    #     restart: always
    #     ports:
    #         - "27017:27017"
    #     environment:
    #         MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
    #         MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    #         MONGO_INITDB_NAME: "mongo-muhna"
    #     logging:
    #         driver: "json-file"
    #         options:
    #             max-size: "10m"
    #             max-file: "5"

    # postgres:
    #     image: postgres:latest
    #     container_name: postgres-muhna
    #     restart: always
    #     ports:
    #         - "5432:5432"
    #     environment:
    #         POSTGRES_USER: ${POSTGRES_USER}
    #         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #     logging:
    #         driver: "json-file"
    #         options:
    #             max-size: "10m"
    #             max-file: "5"

    api:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: api
        restart: always
        ports:
            - "3001:3001"
        volumes:
            - .:/usr/app
        working_dir: /usr/app
        command: ["npm", "run", "start:migrate:prod"]
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "5"
        networks:
            - muhna_network
